openapi: 3.0.3
info:
  title: Password Reset API Contract
  description: API contract for password reset page frontend integration
  version: 1.0.0
  contact:
    email: info@tickedify.com

servers:
  - url: https://dev.tickedify.com
    description: Staging environment
  - url: https://tickedify.com
    description: Production environment

paths:
  /api/account/password-reset/confirm:
    post:
      summary: Confirm password reset with token
      description: |
        Validates the reset token and updates the user's password.
        Token must be valid, not expired (24h), and not previously used.
      operationId: confirmPasswordReset
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - new_password
              properties:
                token:
                  type: string
                  pattern: '^[a-f0-9]{64}$'
                  description: 64-character hexadecimal reset token from email
                  example: "a1b2c3d4e5f6789012345678901234567890123456789012345678901234abcd"
                new_password:
                  type: string
                  minLength: 8
                  description: |
                    New password meeting strength requirements:
                    - Minimum 8 characters
                    - At least 1 uppercase letter
                    - At least 1 digit
                    - At least 1 special character
                  example: "MyNewP@ss123"
      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Password reset successful. You can now log in with your new password."
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - "Invalid token format"
                      - "Password must be at least 8 characters"
              examples:
                invalidTokenFormat:
                  summary: Token format is invalid
                  value:
                    error: "Invalid token format"
                passwordTooShort:
                  summary: Password doesn't meet minimum length
                  value:
                    error: "Password must be at least 8 characters"
        '401':
          description: Unauthorized - token invalid, expired, or already used
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - "Invalid or expired reset token"
                      - "Reset token has expired. Please request a new one."
                      - "Reset token has already been used."
              examples:
                invalidToken:
                  summary: Token not found in database
                  value:
                    error: "Invalid or expired reset token"
                expiredToken:
                  summary: Token is older than 24 hours
                  value:
                    error: "Reset token has expired. Please request a new one."
                usedToken:
                  summary: Token has already been used
                  value:
                    error: "Reset token has already been used."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

components:
  schemas:
    PasswordResetRequest:
      type: object
      required:
        - token
        - new_password
      properties:
        token:
          type: string
          pattern: '^[a-f0-9]{64}$'
          description: Reset token from URL parameter
        new_password:
          type: string
          minLength: 8
          description: New password meeting strength requirements

    PasswordResetSuccess:
      type: object
      properties:
        message:
          type: string
          description: Success message for user

    PasswordResetError:
      type: object
      properties:
        error:
          type: string
          description: Error message describing what went wrong

  securitySchemes: {}

tags:
  - name: Authentication
    description: Password reset authentication endpoints
